### ISSUE TITLE
E-commerce Básico Parte Final

### ISSUE THREAD

**Issue by PabloYR16** [CodeSystem2022/Alibaba-Cuarto-Semestre#7]
El estudiante deberá ingresar a la carpeta semana 1 y realizar la siguiente actividad

1.4 Mostrando detalles finales (Video 04)

Una vez realizado, deberá realizar un commit y luego crear un tag con el nombre SA1-JavaScript-Final
Hacer el push correspondiente.
Generar la PR y notificar al SM para su revisión.

**Comment by angesc2022** [comment]
tarea terminada semana1 video1.4
